FROM ubuntu:trusty
MAINTAINER Somesh Yadav <yadavsms@gmail.com>, Gurpreet Singh <gpsingh1991@yahoo.co.in>

RUN sed -i 's/libtiff5_4.0.3-7ubuntu0.4_amd64.deb/libtiff5_4.0.3-7ubuntu0.6_amd64.deb/' /etc/apt/sources.list
RUN apt-get update && apt-get -y install software-properties-common
RUN add-apt-repository cloud-archive:mitaka
RUN apt-get update
RUN apt-get -y install python-openstackclient python-memcache supervisor mysql-client curl jq
RUN mkdir -p /var/log/supervisor
