FROM {{ docker.registry }}/{{ docker.project }}/{{ docker.base_image }}:{{ docker.tag }}
MAINTAINER Somesh Yadav <yadavsms@gmail.com>, Gurpreet Singh <gpsingh1991@yahoo.co.in>

RUN apt-get update
RUN apt-get -y install neutron-server neutron-plugin-ml2 neutron-plugin-linuxbridge-agent neutron-l3-agent neutron-dhcp-agent neutron-metadata-agent python-neutronclient 

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY run.sh /run.sh
RUN chmod +x /run.sh

EXPOSE 9696

CMD ["/run.sh"]
