FROM ubuntu:trusty
MAINTAINER {{ docker.maintainer }}

RUN apt-get update && apt-get -y install software-properties-common
RUN add-apt-repository cloud-archive:mitaka
RUN apt-get update && apt-get -y dist-upgrade
RUN apt-get -y install python-openstackclient python-memcache supervisor mysql-client curl jq
RUN mkdir -p /var/log/supervisor
