FROM ubuntu:trusty
MAINTAINER Somesh Yadav <yadavsms@gmail.com>, Gurpreet Singh <gpsingh1991@yahoo.co.in>

RUN apt-get update && apt-get -y install software-properties-common
RUN add-apt-repository cloud-archive:mitaka
RUN apt-get update && apt-get -y dist-upgrade
RUN apt-get -y install python-openstackclient python-memcache supervisor mysql-client
RUN mkdir -p /var/log/supervisor
