FROM {{ docker.registry }}/{{ docker.project }}/{{ docker.base_image }}:{{ docker.tag }}
MAINTAINER {{ docker.maintainer }}

RUN apt-get update && apt-get -y install heat-api heat-api-cfn heat-engine

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 9191 9292
