FROM {{ docker.registry }}/{{ docker.project }}/{{ docker.base_image }}:{{ docker.tag }}
MAINTAINER {{ docker.maintainer }}

RUN apt-get update && apt-get -y install memcached

EXPOSE 11211

COPY run.sh /run.sh
RUN chmod +x /run.sh

CMD ["/run.sh"]
