FROM {{ base_fqin }}
MAINTAINER Somesh Yadav <yadavsms@gmail.com>, Gurpreet Singh <gpsingh1991@yahoo.co.in>

RUN apt-get update && apt-get -y install nova-api nova-conductor nova-consoleauth nova-novncproxy nova-scheduler

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 8773 8774 8775
